---
- name: k8s setup
  hosts: k8s
  become: true
  tasks:
    - name: install minikube
      ansible.builtin.shell: |
        curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
        rm minikube-linux-amd64

- name: configure minikube
  hosts: k8s
  become_user: ubuntu
  tasks:
    - name: install minikube
      shell: minikube start --force