---
- name: Failsafe Docker CE and Compose install
  hosts: all
  become: yes
  vars:
    docker_arch: amd64  # or arm64
    docker_codename: "{{ ansible_lsb.codename }}"
  tasks:

    - name: Remove old Docker packages if any
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - docker-buildx-plugin
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install required packages for apt over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Add Docker official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo for supported Ubuntu codename
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu {{ docker_codename }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker CE, CLI, Compose Plugin, Buildx Plugin, and containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        state: latest

    - name: Ensure Docker service is running and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version_output

    - debug:
        var: docker_version_output.stdout
