---
- name: Install Docker CE and Docker Compose (failsafe)
  hosts: all
  become: yes
  vars:
    docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_gpg_key_path: /etc/apt/keyrings/docker.gpg
    docker_repo_file: /etc/apt/sources.list.d/docker.list

  tasks:

    - name: Remove old Docker repository definitions (conflict prevention)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
        - /etc/apt/sources.list.d/docker.list.save
        - /etc/apt/sources.list.d/docker-ce.list
        - /etc/apt/sources.list.d/docker-ce-stable.list

    - name: Ensure apt keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: "{{ docker_gpg_key_url }}"
        dest: "{{ docker_gpg_key_path }}"
        mode: '0644'
      register: docker_key_download

    - name: Convert Docker GPG key to dearmored format
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ docker_gpg_key_path }}"
        stdin: "{{ lookup('file', docker_gpg_key_path) }}"
      when: docker_key_download.changed
      changed_when: docker_key_download.changed

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by={{ docker_gpg_key_path }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present
        update_cache: yes

    - name: Install Docker CE and Docker Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
